---
abstract: 'Filter Log4perl messages based on call frames'
author:
  - 'Patrick Donelan <pat@patspam.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.11
generated_by: 'Dist::Zilla version 1.100711'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Log-Log4perl-Filter-CallerMatch
requires:
  Carp: 0
  File::Find: 0
  File::Temp: 0
  Log::Log4perl: 0
  Log::Log4perl::Config: 0
  Log::Log4perl::Filter: 0
  Test::More: 0
  perl: 5.006
resources:
  repository: http://github.com/pdonelan/log4perl-filter-callermatch
version: 1.100830
